# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=20)),
                ('delivery_address1', models.CharField(max_length=100)),
                ('delivery_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(default='Rivers', max_length=30)),
                ('country', models.CharField(default='Nigeria', max_length=30)),
                ('activation_key', models.CharField(editable=False, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('transaction_id_string', models.CharField(editable=False, max_length=20, unique=True)),
                ('transaction_date', models.DateTimeField(editable=False)),
                ('transaction_complete_date', models.DateTimeField(editable=False, null=True)),
                ('payment_medium', models.CharField(default=0, max_length=1)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('transaction_status', models.CharField(choices=[('0', 'pending'), ('1', 'complete'), ('2', 'others')], default='0', max_length=1)),
                ('items', models.ManyToManyField(to='shop.Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo')),
            ],
        ),
    ]
