# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.CharField(default='Nigeria', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='delivery_address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default='Rivers', max_length=30, null=True),
        ),
    ]
