# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinfo_recovery_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='mobile_phone',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='session_string',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo'),
        ),
    ]
