# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160522_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='payment_medium',
            field=models.CharField(choices=[('0', 'cash_on_delivery'), ('1', 'interswitch'), ('2', 'paypal')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
