# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160528_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('s', 'savings'), ('c', 'current')], default='s', max_length=1)),
                ('name_on_account', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
