# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('old_price', models.FloatField(default=0, null=True)),
                ('sale_price', models.FloatField()),
                ('brief_detail', models.TextField()),
                ('image_file', models.ImageField(null=True, upload_to=shop.models.get_image_upload_path)),
                ('in_stock', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('show_as_new', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('date_added', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(choices=[('0', 'others'), ('1', 'cakes'), ('2', 'gifts')], default='1', max_length=1)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ItemCategory'),
        ),
    ]
