# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('option', models.CharField(max_length=250)),
                ('display', models.BooleanField()),
            ],
        ),
    ]
